version: '3'

services:
  frontend:
    build:
      context: ./frontend
    image: flexforms-frontend
    restart: always
    env_file: ./frontend/.env

  backend:
    build:
      context: ./backend
    image: flexforms-backend
    restart: always
    env_file: ./backend/.env

  nginx:
    image: nginx:alpine3.18
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
